# Generated by Django 5.0 on 2023-12-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Обработано'),
        ),
    ]
