# Generated by Django 5.0 on 2023-12-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_call_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='wantresult',
            name='num',
            field=models.SmallIntegerField(default=1, help_text='1 - обычный; 2 - новый', verbose_name='Какой из wantresult'),
        ),
    ]
