# Generated by Django 5.0 on 2023-12-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_wantresult_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wantresult',
            name='ip',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='IP'),
        ),
    ]
