# Generated by Django 5.0 on 2024-01-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_wantresult_ip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at', 'is_done'], 'verbose_name': 'задача', 'verbose_name_plural': 'задачи'},
        ),
        migrations.AddField(
            model_name='user',
            name='can_be_responsible',
            field=models.BooleanField(default=True, verbose_name='Может быть ответственным?'),
        ),
    ]
