# Generated by Django 5.0 on 2024-01-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_task_options_user_can_be_responsible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='surname',
            field=models.CharField(blank=True, default='Новый клиент', max_length=100, null=True, verbose_name='Фамилия'),
        ),
    ]
