# Generated by Django 5.0 on 2024-01-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_bank_url_alter_bank_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=18, verbose_name='Номер телефона'),
        ),
    ]
