# Generated by Django 5.0 on 2024-01-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_lead_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=18, unique=True, verbose_name='Номер телефона'),
        ),
    ]
