# Generated by Django 5.0 on 2024-01-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_lead_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='event',
            field=models.CharField(blank=True, choices=[('INCOMING', 'Поступил звонок'), ('ACCEPTED', 'Сняли трубку (звонок принят)'), ('COMPLETED', 'Успешно завершен'), ('CANCELLED', 'Звонок сброшен'), ('OUTGOING', 'Исходящий звонок'), ('TRANSFERRED', 'Переведен на другого')], max_length=12, null=True, verbose_name='Событие звонка'),
        ),
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.CharField(blank=True, choices=[('Success', 'Успешно'), ('Missed', 'Пропущенный звонок'), ('Cancel', 'Звонок отменен'), ('Busy', 'Занято'), ('NotAvailable', 'Абонент недоступен'), ('NotAllowed', 'Звонки на это направление запрещены'), ('NotFound', 'Нет такого SIP-номера')], max_length=13, null=True, verbose_name='Статус звонка'),
        ),
    ]
