# Generated by Django 5.0 on 2024-02-07 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_deal_flat_id_deal_complex_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Дата создания')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удалена?')),
            ],
            options={
                'verbose_name': 'компания',
                'verbose_name_plural': 'компании',
                'db_table': 'companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='deal',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='projects',
        ),
        migrations.AddField(
            model_name='lead',
            name='complexes',
            field=models.JSONField(blank=True, null=True, verbose_name='Интересующие комплексы'),
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Дата создания')),
                ('surname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=18, unique=True, verbose_name='Номер телефона')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес электронной почты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удален?')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'партнер',
                'verbose_name_plural': 'партнеры',
                'db_table': 'partners',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.partner', verbose_name='Агент, который привел'),
        ),
    ]
