# Generated by Django 5.0 on 2024-02-07 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_company_remove_deal_seller_remove_lead_projects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.lead', verbose_name='Клиент, который привел'),
        ),
    ]
