# Generated by Django 5.0 on 2024-02-08 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_lead_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.lead', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.partner', verbose_name='Агент'),
        ),
    ]
