# Generated by Django 5.0 on 2024-02-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_lead_client_alter_lead_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exclusive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Дата создания')),
                ('name', models.CharField(max_length=255, verbose_name='Объект')),
                ('object_type', models.CharField(choices=[('commerce', 'Коммерция'), ('flat', 'Недвижимость')], default='flat', max_length=9, verbose_name='Тип')),
                ('sale_type', models.CharField(choices=[('sale', 'Продажа'), ('rent', 'Аренда')], default='sale', max_length=5, verbose_name='Действие')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'эксклюзив',
                'verbose_name_plural': 'эксклюзивы',
                'db_table': 'exclusives',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('-created_at',), 'verbose_name': 'компания', 'verbose_name_plural': 'компании'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['pk', 'fired'], 'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
    ]
