# Generated by Django 5.0 on 2024-02-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_exclusive_alter_company_options_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='exclusive',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
    ]
