# Generated by Django 5.0 on 2024-03-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_exclusive_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Дата создания')),
                ('text', models.TextField(verbose_name='Шаблон сообщения')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'шаблон сообщения',
                'verbose_name_plural': 'шаблоны сообщений',
                'db_table': 'message_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='showing',
            options={'ordering': ['-created_at', 'is_done', '-date_to'], 'verbose_name': 'показ объекта', 'verbose_name_plural': 'показы объектов'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at', 'is_done', '-date_to'], 'verbose_name': 'задача', 'verbose_name_plural': 'задачи'},
        ),
    ]
