# Generated by Django 5.0 on 2024-03-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_messagetemplate_alter_showing_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ['-pk'], 'verbose_name': 'сделка', 'verbose_name_plural': 'сделки'},
        ),
        migrations.AlterModelOptions(
            name='showing',
            options={'ordering': ['-date_to'], 'verbose_name': 'показ объекта', 'verbose_name_plural': 'показы объектов'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-date_to'], 'verbose_name': 'задача', 'verbose_name_plural': 'задачи'},
        ),
        migrations.RemoveField(
            model_name='deal',
            name='complex_id',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='complex_name',
        ),
        migrations.AddField(
            model_name='deal',
            name='bill_date',
            field=models.DateField(blank=True, null=True, verbose_name='Когда передан счет'),
        ),
        migrations.AddField(
            model_name='deal',
            name='com_get_date',
            field=models.DateField(blank=True, null=True, verbose_name='Когда получена выплата'),
        ),
        migrations.AddField(
            model_name='deal',
            name='com_status',
            field=models.CharField(choices=[('wait', 'Ожидаем'), ('receive', 'Получено'), ('think', 'Думают')], default='think', max_length=10, verbose_name='Статус комиссии'),
        ),
        migrations.AddField(
            model_name='deal',
            name='developer',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Застройщик'),
        ),
        migrations.AddField(
            model_name='deal',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Особые отметки'),
        ),
    ]
