# Generated by Django 5.0 on 2024-03-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_deal_options_alter_showing_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='com_paid',
            field=models.FloatField(default=0, verbose_name='Выплаченные средства'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='frm',
            field=models.CharField(blank=True, choices=[('raz', 'Развитие'), ('nmarket', 'Нмаркет'), ('perv', 'Первичка'), ('vdk', 'ВДК'), ('contract', 'Прямой договор')], db_column='from', max_length=10, null=True, verbose_name='Через'),
        ),
    ]
