# Generated by Django 5.0 on 2024-04-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_buyobject_objectcommerce_objectflat_objecthouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='sell_date',
            field=models.DateField(blank=True, null=True, verbose_name='Когда передан счет'),
        ),
    ]
