# Generated by Django 5.0 on 2024-04-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_deal_sell_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='sell_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата сделки'),
        ),
    ]
