# Generated by Django 5.0 on 2024-05-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_partner_company_delete_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='return_to_list',
            field=models.BooleanField(default=False, verbose_name='Вернуть в список сортировки?'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='warm',
            field=models.CharField(blank=True, choices=[('hot', 'Горячий'), ('warm', 'Теплый'), ('cold', 'Холодный'), ('delayed', 'Отложенный спрос'), ('not_client', 'Не клиент'), ('not_call', 'Не дозвонились'), ('not_actual', 'Не актуально')], max_length=11, null=True, verbose_name='Теплота'),
        ),
    ]
