# Generated by Django 5.0 on 2024-05-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_lead_deferred'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='partner_paid',
            field=models.BooleanField(default=False, verbose_name='Партнерские выплачены?'),
        ),
    ]
