# Generated by Django 5.0 on 2024-06-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_deal_partner_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='deal',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='task',
        ),
        migrations.RemoveField(
            model_name='user',
            name='online',
        ),
        migrations.AddField(
            model_name='notification',
            name='item_id',
            field=models.IntegerField(default=0, verbose_name='ID сущности'),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('danger', 'Важно!'), ('warning', 'Предупреждение'), ('normal', 'Обычное'), ('success', 'Успешно')], default='normal', max_length=8, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('lead', 'Лид'), ('deal', 'Сделка'), ('task', 'Задача'), ('showing', 'Показ')], default='task', max_length=8, verbose_name='Тип сущности'),
        ),
    ]
