# Generated by Django 5.0 on 2024-06-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_objectstat_remove_notification_deal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='День рождения'),
        ),
    ]
