# Generated by Django 5.0 on 2024-06-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_objectstat_user_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_id', models.IntegerField()),
                ('phone', models.CharField(max_length=25, verbose_name='Телефон')),
                ('timestamp', models.DateTimeField(verbose_name='Время визита')),
                ('website', models.CharField(blank=True, max_length=255, null=True, verbose_name='Домен сайта')),
                ('page', models.CharField(blank=True, max_length=255, null=True, verbose_name='Страница сайта')),
                ('page_with_parameters', models.CharField(blank=True, help_text='С параметрами', max_length=255, null=True, verbose_name='Страница сайта')),
                ('yid', models.CharField(blank=True, max_length=125, null=True, verbose_name='Идентификатор')),
                ('email', models.JSONField(blank=True, null=True, verbose_name='Почта')),
                ('vk', models.CharField(blank=True, max_length=125, null=True, verbose_name='VK')),
                ('fb', models.CharField(blank=True, max_length=125, null=True, verbose_name='Facebook')),
                ('insta', models.CharField(blank=True, max_length=125, null=True, verbose_name='Instagram')),
                ('ok', models.CharField(blank=True, max_length=125, null=True, verbose_name='OK')),
                ('utm_source', models.CharField(max_length=125)),
                ('utm_medium', models.CharField(max_length=125)),
                ('utm_campaign', models.CharField(max_length=125)),
                ('utm_term', models.CharField(max_length=125)),
                ('utm_content', models.CharField(max_length=125)),
                ('referer', models.CharField(max_length=125)),
                ('ip', models.CharField(max_length=16)),
                ('stock_key', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'dmp.one',
                'verbose_name_plural': 'dmp.one`s',
                'db_table': 'dmp_one',
            },
        ),
    ]
