# Generated by Django 5.0 on 2024-06-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_objectstat_dmp'),
    ]

    operations = [
        #migrations.CreateModel(
        #    name='ObjectStat',
        #    fields=[
        #        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #        ('contacts', models.IntegerField(default=0, verbose_name='Совершившие контакты')),
        #        ('favorites', models.IntegerField(default=0, verbose_name='Избранное')),
        #        ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
        #        ('date', models.DateField(verbose_name='Дата')),
        #    ],
        #    options={
        #        'verbose_name': 'статистика по объекту',
        #        'verbose_name_plural': 'статистика по объектам',
        #        'db_table': 'object_stats',
        #        'managed': False,
        #    },
        #),
        migrations.AddField(
            model_name='deal',
            name='planned_date',
            field=models.DateField(blank=True, null=True, verbose_name='Планируемая дата получения денег'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='frm',
            field=models.CharField(blank=True, choices=[('raz', 'Развитие'), ('nmarket', 'Нмаркет'), ('perv', 'Первичка'), ('vdk', 'ВДК'), ('contract', 'Прямой договор'), ('city', 'Сити-центр')], db_column='from', max_length=10, null=True, verbose_name='Через'),
        ),
    ]
