# Generated by Django 5.0 on 2024-07-11 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_objectstat_deal_planned_date_alter_deal_frm'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ипотечный брокер'),
        ),
        migrations.AddField(
            model_name='deal',
            name='broker_status',
            field=models.CharField(blank=True, choices=[('consultation', 'Консультация'), ('collect_docs', 'Сбор документов'), ('review', 'Рассмотрение'), ('estate', 'Подбор недвижимости')], max_length=13, null=True, verbose_name='Ипотечный статус'),
        ),
        migrations.AddField(
            model_name='user',
            name='broker',
            field=models.BooleanField(default=False, verbose_name='Ипотечный брокер?'),
        ),
    ]
