# Generated by Django 5.0 on 2024-07-19 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_deal_broker_deal_broker_status_user_broker'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='broker_status',
            field=models.CharField(blank=True, choices=[('consultation', 'Консультация'), ('collect_docs', 'Сбор документов'), ('review', 'Рассмотрение'), ('estate', 'Подбор недвижимости'), ('deal', 'Сделка')], max_length=13, null=True, verbose_name='Ипотечный статус'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='warm',
            field=models.CharField(blank=True, choices=[('hot', 'Горячий'), ('warm', 'Теплый'), ('cold', 'Холодный'), ('not_client', 'Не клиент'), ('not_call', 'Не дозвонились'), ('not_actual', 'Не актуально')], max_length=11, null=True, verbose_name='Теплота'),
        ),
    ]
