# Generated by Django 5.0 on 2024-07-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_notification_created_by_alter_deal_broker_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='broker_status',
            field=models.CharField(blank=True, choices=[('consultation', 'Консультация'), ('collect_docs', 'Сбор документов'), ('review', 'Рассмотрение'), ('estate', 'Подбор недвижимости'), ('deal', 'Сделка'), ('bank_decline', 'Отказ банка'), ('client_decline', 'Отказ клиента')], max_length=15, null=True, verbose_name='Ипотечный статус'),
        ),
    ]
