# Generated by Django 5.0 on 2024-08-10 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_objectstat_options_objectphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts', models.IntegerField(default=0, verbose_name='Совершившие контакты')),
                ('favorites', models.IntegerField(default=0, verbose_name='Избранное')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('date', models.DateField(verbose_name='Дата')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.buyobject', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'статистика по объекту',
                'verbose_name_plural': 'статистика по объектам',
                'db_table': 'object_stats',
            },
        ),
    ]
