# Generated by Django 5.0 on 2024-08-24 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_objectstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='buy_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.buyobject', verbose_name='Объект'),
        ),
    ]
