# Generated by Django 5.0 on 2024-09-01 08:46

import django.db.models.deletion
import main.models.avito_call
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0037_deal_buy_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvitoCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet', models.CharField(choices=[('old', 'Вторичка'), ('new_1', 'Первичка 1'), ('new_2', 'Первичка 2')], default='old', max_length=6, verbose_name='Из какого кабинета')),
                ('buyer_phone', models.CharField(max_length=15, verbose_name='Номер покупателя')),
                ('call_id', models.IntegerField(default=0, verbose_name='ID звонка')),
                ('call_time', models.DateTimeField(verbose_name='Время звонка')),
                ('seller_phone', models.CharField(max_length=15, verbose_name='Номер продавца')),
                ('talk', models.IntegerField(default=0, verbose_name='Длительность разговора')),
                ('virtual_phone', models.CharField(max_length=15, verbose_name='Виртуальный номер')),
                ('waiting', models.IntegerField(default=0, verbose_name='Длительность ожидания')),
                ('rec_file', models.FileField(blank=True, null=True, upload_to=main.models.avito_call.directory_path, verbose_name='Запись разговора')),
            ],
            options={
                'verbose_name': 'звонок из авито',
                'verbose_name_plural': 'звонки из авито',
                'db_table': 'avito_calls',
            },
        ),
        migrations.RenameField(
            model_name='deal',
            old_name='mortgage',
            new_name='mrtg',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='onlineconfirm',
        ),
        migrations.AddField(
            model_name='bank',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал'),
        ),
        migrations.AddField(
            model_name='bank',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Кто обновил'),
        ),
        migrations.AddField(
            model_name='comment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал'),
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Кто обновил'),
        ),
        migrations.AddField(
            model_name='deal',
            name='spam',
            field=models.BooleanField(default=False, verbose_name='Спам?'),
        ),
        migrations.AddField(
            model_name='funnel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал'),
        ),
        migrations.AddField(
            model_name='funnel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Кто обновил'),
        ),
        migrations.AddField(
            model_name='lead',
            name='spam',
            field=models.BooleanField(default=False, verbose_name='Спам?'),
        ),
        migrations.AddField(
            model_name='partner',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал'),
        ),
        migrations.AddField(
            model_name='partner',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Кто обновил'),
        ),
        migrations.AddField(
            model_name='stage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал'),
        ),
        migrations.AddField(
            model_name='stage',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Кто обновил'),
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('agent', models.FloatField(default=0, verbose_name='Комиссия агентства')),
                ('paid', models.FloatField(default=0, verbose_name='Выплаченные средства')),
                ('manager', models.FloatField(default=0, verbose_name='Комиссия менеджера')),
                ('get', models.BooleanField(default=False, verbose_name='Выплата получена')),
                ('get_date', models.DateField(blank=True, null=True, verbose_name='Когда получена выплата')),
                ('status', models.CharField(choices=[('wait', 'Ожидаем'), ('receive', 'Получено'), ('think', 'Думают')], default='think', max_length=10, verbose_name='Статус комиссии')),
                ('bill_date', models.DateField(blank=True, null=True, verbose_name='Когда передан счет')),
                ('planned_date', models.DateField(blank=True, null=True, verbose_name='Планируемая дата получения денег')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.deal', verbose_name='Сделка')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Кто обновил')),
            ],
            options={
                'verbose_name': 'деньги по сделке',
                'verbose_name_plural': 'деньги по сделкам',
                'db_table': 'moneys',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Mortgage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('max', models.FloatField(default=0, verbose_name='Максимально одобренная сумма')),
                ('size', models.FloatField(default=0, verbose_name='Выданная банком сумма')),
                ('broker_status', models.CharField(blank=True, choices=[('consultation', 'Консультация'), ('collect_docs', 'Сбор документов'), ('review', 'Рассмотрение'), ('estate', 'Подбор недвижимости'), ('deal', 'Сделка'), ('bank_decline', 'Отказ банка'), ('client_decline', 'Отказ клиента')], max_length=15, null=True, verbose_name='Ипотечный статус')),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ипотечный брокер')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.deal', verbose_name='Сделка')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Кто обновил')),
            ],
            options={
                'verbose_name': 'ипотека',
                'verbose_name_plural': 'ипотеки',
                'db_table': 'mortgages',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='UserLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Дата создания')),
                ('object_id', models.IntegerField(default=0, verbose_name='ID объекта')),
                ('fields', models.JSONField(blank=True, null=True)),
                ('action_flag', models.PositiveSmallIntegerField(choices=[(1, 'Изменено'), (2, 'Удалено')], default=1, verbose_name='Тип события')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Тип сущности')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'событие',
                'verbose_name_plural': 'события',
                'db_table': 'user_log_entry',
                'ordering': ['created_at'],
            },
        ),
    ]
