# Generated by Django 5.0 on 2024-09-01 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_avitocall_rename_mortgage_deal_mrtg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mortgage',
            old_name='size',
            new_name='sum',
        ),
    ]
