# Generated by Django 5.1.5 on 2025-02-26 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_building_apartment_residentialcomplex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='Apartment',
            name='section',
            field=models.IntegerField(null=True, default=1),
            
        ),
    ]
