# Generated by Django 5.1.5 on 2025-03-18 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_addSectionToAppartments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'verbose_name': 'Квартиры', 'verbose_name_plural': 'Квартиры'},
        ),
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'Дома', 'verbose_name_plural': 'Дома'},
        ),
        migrations.AddField(
            model_name='apartment',
            name='terrace',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='building',
            name='complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='main.complex'),
        ),
    ]
