# Generated by Django 5.1.5 on 2025-03-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_alter_apartment_options_alter_building_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='decoration',
            field=models.CharField(choices=[('Без отделки', 'Без отделки'), ('Предчистовая', 'Предчистовая'), ('Чистовая', 'Чистовая')], default='Без отделки', max_length=13, verbose_name='Отделка'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='import_id',
            field=models.BigIntegerField(default=0, verbose_name='Import ID'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='kitchen_space',
            field=models.FloatField(default=0, verbose_name='Площадь кухни'),
        ),
        migrations.AddField(
            model_name='building',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='alternative_description',
            field=models.TextField(blank=True, help_text='Если описание квартир перезаписывать не надо, то лучше оставить пустым', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='building',
            name='avito_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='city',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='building',
            name='description',
            field=models.TextField(blank=True, help_text='Если описание квартир перезаписывать не надо, то лучше оставить пустым', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='building',
            name='material',
            field=models.CharField(blank=True, choices=[('Кирпичный', 'Кирпичный'), ('Панельный', 'Панельный'), ('Блочный', 'Блочный'), ('Монолитный', 'Монолитный'), ('Монолитно-кирпичный', 'Монолитно-кирпичный')], max_length=20, null=True, verbose_name='Материал стен'),
        ),
        migrations.AddField(
            model_name='building',
            name='region',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='complex',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complex',
            name='alternative_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complex',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complex',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='rooms',
            field=models.CharField(choices=[('Студия', 'Студия'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10 и более', '10 и более'), ('Своб.планировка', 'Своб.планировка')], default='1', verbose_name='Количество комнат'),
        ),
    ]
