# Generated by Django 5.1.5 on 2025-03-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_remove_apartment_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='rooms',
            field=models.CharField(choices=[('Студия', 'Студия'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10 и более', '10 и более'), ('Своб.планировка', 'Своб.планировка')], default='1', verbose_name='Количество комнат'),
        ),
    ]
