# Generated by Django 5.1.5 on 2025-03-18 18:44

import django.db.models.deletion
import main.models.apartment_photo
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_apartment_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(help_text='Фото формата .png, .jpg, .jpeg. Не более 2мб', upload_to=main.models.apartment_photo.directory_path, verbose_name='Фото')),
                ('sort', models.IntegerField(default=0, verbose_name='Порядок')),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.apartment', verbose_name='Квартира')),
            ],
            options={
                'verbose_name': 'фото объявления',
                'verbose_name_plural': 'фотографии объявлений',
                'db_table': 'apartment_photo',
            },
        ),
    ]
