# Generated by Django 5.1.5 on 2025-03-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_apartmentphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Публиковать в фид'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='apartment_type',
            field=models.CharField(max_length=255, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='area',
            field=models.FloatField(verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='col',
            field=models.IntegerField(verbose_name='Колонка (для шахматки)'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='floor',
            field=models.IntegerField(verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='number',
            field=models.CharField(max_length=10, verbose_name='Номер квартиры'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='section',
            field=models.IntegerField(default=1, null=True, verbose_name='Секция (подъезд)'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='status',
            field=models.CharField(choices=[('available', 'Свободно'), ('reserved', 'Платная бронь'), ('shortReserved', 'Короткая бронь'), ('sold', 'Продана')], default='available', max_length=15, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='str',
            field=models.IntegerField(verbose_name='Строка (для шахматки, она же этаж)'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='terrace',
            field=models.BooleanField(default=False, verbose_name='Терраса'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='window_orientation',
            field=models.CharField(max_length=255, verbose_name='Вид из окна'),
        ),
    ]
