# Generated by Django 5.1.5 on 2025-04-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_alter_building_address_alter_complex_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='apartment_type',
            field=models.CharField(choices=[('Студия', 'Студия'), ('1-комнатная', '1-комнатная'), ('2Е – евродвушка', '2Е – евродвушка'), ('2-комнатная', '2-комнатная'), ('3Е – евротрешка', '3Е – евротрешка'), ('3-комнатная', '3-комнатная'), ('4Е - еврочетырешка', '4Е - еврочетырешка'), ('4-комнатная', '4-комнатная'), ('5Е – пятикомнатная евро', '5Е – пятикомнатная евро'), ('Многокомнатная', 'Многокомнатная'), ('Свободная планировка', 'Свободная планировка')], default='Студия', max_length=255, verbose_name='Тип'),
        ),
    ]
