# Generated by Django 5.1.5 on 2025-04-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_alter_apartment_apartment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='status',
            field=models.CharField(choices=[('available', 'Свободно'), ('reserved', 'Платная бронь'), ('shortReserved', 'Короткая бронь'), ('sold', 'Продана'), ('closedToSell', 'Закрыто к продажу')], default='available', max_length=15, verbose_name='Статус'),
        ),
    ]
