# Generated by Django 5.1.5 on 2025-05-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_alter_apartment_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='living_square',
            field=models.FloatField(default=0, verbose_name='Жилая площадь'),
        ),
    ]
